# change the followings to match your Github username and repo name
# baseurl: "/wip-neponset-river-in-time" # the name of your github repo
# url: "https://BCDigSchol.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "A River in Time&#58; Environmental Histories on the Neponset River"
description: Jekyll site for the Neponset River in Time Project @ Boston College

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: About
    link: about
  - title: Mapping Space
    link: mapping-space
  - title: Telling Stories
    link: telling-stories
  - title: Neponset "Now"
    link: neponset-now
  - title: Resources
    submenu:
      - title: Further Reading
        link: further-reading
      - title: Works Cited
        link: works-cited
      - title: Maps
        link: maps

# sets whether a search bar appears on the site header
# NOTE, you will have to increase the site of teh $site-header-height in _sass/theme-settings.scss to to see the search bar
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: "A River in Time: Environmental Histories on the Neponset River | CC BY-NC License"
footer-submessage:  By Laura Clerx, Conevery Valencius, and Asa Ackerly, with the Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
